---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-dev
  chart:
    git: ssh://git@github.com:morbargig/echo-app-k8s-chart
    path: charts/echo
    ref: dev
  values:
    image:
<<<<<<< HEAD
      repository: morbargig/echo-app # us.gcr.io/cloud-285915/newechoapp
      tag: "dev-kdzwicz7"
=======
      repository: us.gcr.io/cloud-285915/newechoapp
      tag: "dev-goojxbw7"
>>>>>>> 6f686a9b26f0a0eb7de3b9230f29ca1e41bdcd69
    replicaCount: 1
    # app:
    # - port:  3000
    # service: 
    # - targetPort: 3000
