---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-dev
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-dev
  chart:
    git: ssh://git@github.com:morbargig/echo-app-k8s-chart
    path: charts/echo
    ref: dev
  values:
    image:
      repository: us.gcr.io/cloud-285915/newechoapp
      tag: ""
    replicaCount: 1
    # app:
    # - port:  3000
    # service: 
    # - targetPort: 3000
