# Default values for echo-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: morbargig/echo-app
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "dev-x3oze1nu"

mongodburl: mongodb://root:QCo8MLyHmX@mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017,mongodb-2.mongodb-headless.default.svc.cluster.local:27017/admin?authSource=admin&gssapiServiceName=mongodb

app:
  name : echo-app
  port: "3000"
  image: morbargig/echo-app # us.gcr.io/cloud-285915/newechoapp
  env:
    port: 
      key: PORT
      value: "3000"
    loglevel: 
      key: LOGLEVEL
      value: info
    persist: 
      key: PERSIST
      value: false
    mongodburl: 
      key: MONGODBURL
      value: null
    dbname: 
      key: DBNAME
      value: echo
  mongodburlsecret: mongo--secret
  command: [npm, start]
        

service:
  name: load-blancer
  type: LoadBalancer
  port: 3000
  targetPort: 3000


ingress:
  enabled: false
  annotations: 
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: morbargig.giize.com
      paths: [backend]
  tls: 
    - secretName: echo-tlsy
    - hosts:
      - morbargig.giize.com


autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

################### not in used #########################

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""



serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000