---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-prod
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.1
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:morbargig/echo-app-k8s-chart
    path: charts/echo
    ref: master
  values:
    image:
      repository: docker.io/morbargig/echo-app
      # us.gcr.io/cloud-285915/newechoapp
      tag: 0.1.0
    # replicaCount: 3
    # app:
    # - port:  3000
    # service: 
    # - targetPort: 3000
    #   port: 80
