apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}--pod
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:

    
      app: {{ .Release.Name }}--app
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}--app
    spec:
      containers:
        - name: {{ .Release.Name }}--app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          env:
            {{- range .Values.app.env }}
          - name: "{{ .key  }}" #| upper
            value : "{{ .value }}"
            {{- end }}    
          - name: MONGODBURL
            valueFrom:
              secretKeyRef:
                name: {{ .Values.app.mongodburlsecret }}
                key: mongodburl
          ports:
           - containerPort: {{ .Values.app.port }}
          command: 
          {{- range .Values.app.command }} 
          - "{{ . }}" 
          {{- end }}

