apiVersion: v1
kind: Pod
metadata:
  annotations:
    prometheus.io/port: '9898'
    prometheus.io/scrape: 'true'
  labels:
    app: podinfo
    pod-template-hash: 79b658d5b
    release: default-podinfo
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  name: {{ template "fullname" . }}
  ownerReferences:
    - apiVersion: apps/v1
      blockOwnerDeletion: true
      controller: true
      kind: ReplicaSet
      name: default-podinfo-79b658d5b
      uid: 1a8e94f1-d24a-415c-9d1f-93e2959ee03e
spec:
  containers:
    - command:
        - ./podinfo
        - '--port=9898'
        - '--port-metrics=9797'
        - '--grpc-port=9999'
        - '--grpc-service-name=podinfo'
        - '--level=info'
        - '--random-delay=false'
        - '--random-error=false'
      env:
        - name: PODINFO_UI_COLOR
      image: 'stefanprodan/podinfo:3.2.0'
      imagePullPolicy: IfNotPresent
      livenessProbe:
        exec:
          command:
            - podcli
            - check
            - http
            - 'localhost:9898/healthz'
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      name: podinfo
      ports:
        - containerPort: 9898
          name: http
          protocol: TCP
        - containerPort: 9797
          name: http-metrics
          protocol: TCP
        - containerPort: 9999
          name: grpc
          protocol: TCP
      readinessProbe:
        exec:
          command:
            - podcli
            - check
            - http
            - 'localhost:9898/readyz'
        failureThreshold: 3
        initialDelaySeconds: 1
        periodSeconds: 10
        successThreshold: 1
        timeoutSeconds: 5
      resources:
        requests:
          cpu: 1m
          memory: 16Mi
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: default-token-xtn7k
          readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: gke-cluster-1-default-pool-271e3d39-mjjw
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - emptyDir: {}
      name: data
    - name: default-token-xtn7k
      secret:
        defaultMode: 420
        secretName: default-token-xtn7k
