

# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo--secret
# type: "Opaque"
# data:
#   mongodburl: {{ .Values.mongodburl | b64enc }}
# stringData:
#   mongodburl: mongodb://root:QCo8MLyHmX@mongodb-0.mongodb-headless.default.svc.cluster.local:27017,mongodb-1.mongodb-headless.default.svc.cluster.local:27017,mongodb-2.mongodb-headless.default.svc.cluster.local:27017/admin?authSource=admin&gssapiServiceName=mongodb



      
