apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}--srv
  labels:
    app : {{ .Release.Name }}--app
spec:
  {{- if not .Values.ingress.enabled }}
  # externalTrafficPolicy: Local
  type: {{ .Values.service.type }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
      protocol: TCP
  selector:
    app: {{ .Release.Name }}--app

